# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200, verbose_name='entry title')),
                ('body_text', models.CharField(max_length=200, verbose_name='entry body')),
                ('published_date', models.DateTimeField(verbose_name='published date')),
            ],
        ),
        migrations.CreateModel(
            name='EntryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('modified_date', models.DateTimeField(verbose_name='date modified')),
                ('name_text', models.CharField(max_length=200, verbose_name='journal name')),
                ('description_text', models.CharField(max_length=200, verbose_name='journal description')),
                ('hidden_boolean', models.BooleanField(default=False, verbose_name='hidden')),
                ('deleted_boolean', models.BooleanField(default=False, verbose_name='deleted')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_text', models.CharField(max_length=200, verbose_name='email')),
                ('password_hash', models.CharField(max_length=200, verbose_name='password')),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.User'),
        ),
        migrations.AddField(
            model_name='entrylog',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.Journal'),
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.EntryLog'),
        ),
    ]
