# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='deleted_boolean',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='hidden_boolean',
        ),
        migrations.AddField(
            model_name='entry',
            name='deleted_boolean',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='entry',
            name='hidden_boolean',
            field=models.BooleanField(default=False, verbose_name='hidden'),
        ),
    ]
