# Generated by Django 2.0.dev20170827005745 on 2017-10-12 03:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='published_date',
        ),
        migrations.AddField(
            model_name='entry',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date'),
        ),
    ]
