# Generated by Django 2.0.dev20170827005745 on 2017-10-12 03:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_auto_20171012_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='published date'),
        ),
    ]
