# Generated by Django 2.0.dev20170827005745 on 2017-10-19 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_auto_20171012_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['created_date']},
        ),
    ]
